### ISSUE TITLE
prune_transcripts.py Error Message

### ISSUE THREAD

**Issue by ghost** [alexfields/ORF-RATER#11]
Hello,

We are receiving the following error when running the prune_transcripts script:

`(ENV) Rhaegal:ORF-RATER matamala$ python prune_transcripts.py --inbed /Users/matamala/Desktop/MM9_Files/mm9_TOME.bed12 -p 2 /Users/matamala/Desktop/MM9_Files/mm9_REFGEN.fa /Users/matamala/Desktop/MM9_Files/Final_Alignment_BAM.bam > logfile.out
Traceback (most recent call last):
  File "prune_transcripts.py", line 168, in <module>
    tid_summary = pd.concat(workers.map(_get_tid_info, bedlinedict.keys()))
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: invalid literal for int() with base 4: ''`

**Comment by marcasriv** [comment]
Hello, 

I am finding the same issue. Did you eventually find a workaround?

Thank you!

Marina

**Comment by alexfields** [comment]
I think this would happen if a transcript extends past the end of the reference in the fasta (though perhaps it could be happening for some other reason). It might be worth identifying for each reference the maximum end point for any transcript in your BED file, and comparing against the length of that reference in your fasta file.
