### ISSUE TITLE
prune_transcripts mapping information not recorded

### ISSUE THREAD

**Issue by jfreimer** [alexfields/ORF-RATER#2]
Hi,
I'm getting the following error while trying to run prune_transcripts.py. I downloaded the bed file from the UCSC table browser. 

```
 [jfreimer@h1 ORF-RATER]$ python prune_transcripts.py --inbed gencode.vM7.basic.bed -p 1 --minlen 28 --maxlen 30 -v GRCm38.primary_assembly.genome.fa ribo1/accepted_hits.bam ribo2/accepted_hits.bam > logfile.out
Traceback (most recent call last):
  File "prune_transcripts.py", line 161, in <module>
    tid_summary = pd.concat(workers.map(_get_tid_info, bedlinedict.keys()))
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: mapping information not recorded in index or index not available
```

**Comment by alexfields** [comment]
This error might arise if your BAM files are not indexed. Do the following files exist?

```
ribo1/accepted_hits.bam.bai
ribo2/accepted_hits.bam.bai
```

If not, you can generate the index files by running from command line:

```
samtools index ribo1/accepted_hits.bam
samtools index ribo2/accepted_hits.bam
```

Please reopen the issue if this does not solve the problem (e.g. if the *.bam.bai files already existed).
